name: movie_genre_model
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - pip=25.3
  - typer=0.20.0
  - loguru=0.7.3
  - tqdm=4.67.1
  - ipython=9.7.0
  - jupyterlab=4.4.10
  - matplotlib=3.10.7
  - notebook=7.4.7
  - numpy=2.3.4
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - ruff=0.14.5
  - pytest=9.0.1
  - seaborn=0.13.1
  - pip:
      - python-dotenv==1.2.1
      - mkdocs==1.6.1
      - mlflow==2.14.0  # Optional: for experiment tracking and model management
      - -e .
