name: movie_genre_model
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - pip=25.3
  - typer=0.20.0
  - loguru=0.7.3
  - tqdm=4.67.1
  - ipython=9.7.0
  - jupyterlab=4.4.10
  - matplotlib=3.10.7
  - notebook=7.4.7
  - numpy<2.0.0
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - ruff=0.14.5
  - pytest=9.0.1
  - pytest-cov=6.0.0
  - pre-commit=3.8.0
  - seaborn=0.13.1
  - pip:
      - torch>=2.0.0
      - python-dotenv==1.2.1
      - mkdocs==1.6.1
      - mlflow==2.14.0  # Optional: for experiment tracking and model management
      - flask==3.0.0
      - flask-cors==4.0.0
      - gunicorn==21.2.0
      - fastapi==0.115.0
      - uvicorn[standard]==0.30.0
      - pydantic>=2.2.0
      - pydantic-settings>=2.0.0
      # - xgboost==2.1.3 
      - -e .
